### PR TITLE
Leverage new `pickScaleRule` util when deleting scale rules

### LINKED ISSUE #495: An error occurs when executing "Delete Scale Rule..." command for the revision from command palette
**OS:** All
**Build Version:** 20231016.3
**Regression:** Not a Regression

**Repro Steps:**
1. Create a container app.
2. Make sure the revision mode is multiple.
3. Create scale rules.
4. F1 -> Click "Delete Scale Rule..." -> Select a container apps environment -> Select a container app -> Select a revision contains scale rules (Not the latest one).
5. Check whether no error occurs.

**Expect:**
No error occurs.

**Actual:**
An error occurs.
Screenshot 2023-10-17 at 09 20 18

**More Info:**

1. This issue doesn't reproduce when executing "Delete Scale Rule..." command for the latest revision.
2. This issue doesn't reproduce when executing "Delete Scale Rule..." action from context menu.

### PR DESCRIPTION
**Pull request by MicroFish91**
Closes #495, #496

### CODE REVIEW

File: src/commands/scaling/scaleRule/ScaleRuleListStep.ts [hunk 1]
```diff
@@ -18,6 +18,7 @@ export class ScaleRuleListStep extends AzureWizardPromptStep<ScaleRuleContext> {
     }
 
     private async getPicks(context: ScaleRuleContext): Promise<IAzureQuickPickItem<ScaleRule>[] | undefined> {
+        // Todo: Expand support for multiple revisions
```
Comment (motm32) [inline src/commands/scaling/scaleRule/ScaleRuleListStep.ts:21]: Don't think this is being used anywhere else. May want to add a comment on why we are still keeping this file.

Comment (MicroFish91) [reply src/commands/scaling/scaleRule/ScaleRuleListStep.ts:21]: Maybe we should just remove it then and add it back in when we need it again?

Comment (motm32) [reply src/commands/scaling/scaleRule/ScaleRuleListStep.ts:21]: Sounds good to me!

**Review by motm32 — APPROVED** [review]
