### PR TITLE
Activity children and output log support for `deployWorkspaceProject`

### LINKED ISSUE #425: Implement the `Click2Run` command
Create a workspace command that allows a user to deploy their workspace project to ACA, while providing a minimal number of prompts/configurations for easy deployment.  We will leverage the ACR tasks method for deploying new images.  Project will require a `Dockerfile` to deploy.

**Todo**:
- [x] Determine which values can be defaulted/assumed (Team - 8/10)
- [x] Enable creating an Azure Container Registry if the user doesn't already have one available (@motm32)
- [ ] Implement the command/contract (@MicroFish91)

### LINKED ISSUE #457: Fail to execute "Deploy Project from Workspace..." command
**OS:** Win10
**Build Version:** 20230920.3
**Regression:** Not a Regression

**Repro Steps:**
1. In VS Code, open a project folder with a Dockerfile in it.
2. F1 -> Select "Azure Container Apps: Deploy Project from Workspace..." -> Enter a name for new container app resources -> Enter.
3. Check whether succeeds to execute "Deploy Project from Workspace..." command or not.

**Expect:**
Succeed to execute "Deploy Project from Workspace..." command.

**Actual:**
Fail to execute "Deploy Project from Workspace..." command.
image

### PR DESCRIPTION
**Pull request by MicroFish91**
Closes #425 
Closes #457 

Additions:
- Add output log/activity children to important steps of the `deployWorkspaceProject` flow

[demo](https://microsoft-my.sharepoint.com/:v:/p/matfisher/EXziurykRO9Bhmg_Yp3Nq0oBx02_-ZC2CNzM8EWf_gEF5Q?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0RpcmVjdCJ9fQ&e=NVcKcB&xsdata=MDV8MDF8fDQ1ZGViOTg0MjIzZTQ1MGE3NDE2MDhkYmFhNmZjMDcxfDcyZjk4OGJmODZmMTQxYWY5MWFiMmQ3Y2QwMTFkYjQ3fDB8MHw2MzgyOTExNjkxNDk4MDk2ODZ8VW5rbm93bnxWR1ZoYlhOVFpXTjFjbWwwZVZObGNuWnBZMlY4ZXlKV0lqb2lNQzR3TGpBd01EQWlMQ0pRSWpvaVYybHVNeklpTENKQlRpSTZJazkwYUdWeUlpd2lWMVFpT2pFeGZRPT18MXxMMk5vWVhSekx6RTVPbTFsWlhScGJtZGZUa2RhYVZsVVNYZFpNbFYwVFhwa2FFNURNREJQVkVGM1RGUm9hVmxYV1hST2VtaHJUVVJhYlZwVWJHbE5SRlpxUUhSb2NtVmhaQzUyTWk5dFpYTnpZV2RsY3k4eE5qa3pOVEU1TWpBMU9UYzJ8ZmUzZDBjMGM4MTgxNDliOTc0MTYwOGRiYWE2ZmMwNzF8MmNhYWI0Y2RhOGFiNDA4YmIyMzYwMGYzN2FkZmM2MGU%3D&sdata=YzZZMFNnT3c2ZE5RTDlmbFBJbW5JYWZGR2JMMW51SUc3T1BHKzFEbTJwST0%3D&ovuser=72f988bf-86f1-41af-91ab-2d7cd011db47%2Cmatfisher%40microsoft.com)

### CODE REVIEW

File: src/commands/deployImage/imageSource/buildImageInAzure/BuildImageStep.ts [hunk 1]
```diff
@@ -40,10 +42,36 @@ export class BuildImageStep extends AzureWizardExecuteStep<IBuildImageInAzureCon
             context.errorHandling.suppressDisplay = true;
             throw new Error(errorMessage);
         }
+
+        // Need to place this outside of 'initSuccessOutput' so we can use the image after it has had a chance to become defined
+        (this.success.output as string[])?.push(localize('useImage', 'Using image "{0}".', context.image));
```
Comment (nturinski) [inline src/commands/deployImage/imageSource/buildImageInAzure/BuildImageStep.ts:47]: I'm not entirely sure why this is part of the `successOutput`. Wouldn't you want this to be displayed even if it fails? I'm also not sure what's the difference between `context.image` and `context.imageName`?

File: src/commands/deployImage/imageSource/buildImageInAzure/RunStep.ts [hunk 2]
```diff
@@ -38,6 +42,22 @@ export class RunStep extends AzureWizardExecuteStep<IBuildImageInAzureContext> {
...
+    }
+
+    protected initSuccessOutput(): ExecuteActivityOutput {
+        // Skip here, success will be output by the build image step
+        return {};
+    }
+
+    protected initFailOutput(context: IBuildImageInAzureContext): ExecuteActivityOutput {
+        return {
+            item: new GenericTreeItem(undefined, {
```
Comment (nturinski) [inline src/commands/deployImage/imageSource/buildImageInAzure/RunStep.ts:55]: The failure won't be output by the build image step also?

File: src/commands/deployImage/imageSource/containerRegistry/acr/createAcr/RegistryCreateStep.ts [hunk 3]
```diff
@@ -30,6 +33,28 @@ export class RegistryCreateStep extends AzureWizardExecuteStep<CreateAcrContext>
...
     public shouldExecute(context: CreateAcrContext): boolean {
-        return !!context.newRegistryName && !!context.newRegistrySku;
+        return !context.registry;
+    }
+
+    protected initSuccessOutput(context: CreateAcrContext): ExecuteActivityOutput {
+        return {
+            item: new GenericTreeItem(undefined, {
+                contextValue: createActivityChildContext(['registryCreateStep', activitySuccessContext]),
+                label: localize('createRegistryLabel', 'Create Azure Container Registry "{0}"', context.newRegistryName),
```
Comment (nturinski) [inline src/commands/deployImage/imageSource/containerRegistry/acr/createAcr/RegistryCreateStep.ts:43]: I'd just say "Create registry". Bit weird that you have all of the other resources be generic, and this one is branded.

File: src/commands/deployWorkspaceProject/DeployWorkspaceProjectSaveSettingsStep.ts [hunk 4]
```diff
@@ -27,4 +36,26 @@ export class DeployWorkspaceProjectSaveSettingsStep extends AzureWizardExecuteSt
...
     }
+
+    protected initSuccessOutput(): ExecuteActivityOutput {
+        return {
+            item: new GenericTreeItem(undefined, {
+                contextValue: createActivityChildContext(['deployWorkspaceProjectSaveSettingsStep', activitySuccessContext]),
+                label: saveSettingsLabel,
+                iconPath: activitySuccessIcon
+            }),
+            output: localize('savedSettingsSuccess', 'Saved deployment settings to workspace: "{0}".', relativeSettingsFilePath)
```
Comment (nturinski) [inline src/commands/deployWorkspaceProject/DeployWorkspaceProjectSaveSettingsStep.ts:47]: Weird that this one has a colon, but the other resources output messages do not.

File: src/commands/deployWorkspaceProject/deployWorkspaceProject.ts [hunk 5]
```diff
@@ -67,13 +67,13 @@ export async function deployWorkspaceProject(context: IActionContext): Promise<v
...
-        //         contextValue: createActivityChildContext(['useExistingResourceGroup', activitySuccessContext]),
-        //         label: localize('useResourceGroup', 'Use resource group "{0}"', resourceGroupName),
-        //         iconPath: activitySuccessIcon
-        //     })
-        // );
+        wizardContext.activityChildren?.push(
+            new GenericTreeItem(undefined, {
+                contextValue: createActivityChildContext(['useExistingResourceGroup', activitySuccessContext]),
+                label: localize('useResourceGroup', 'Use resource group "{0}"', resourceGroupName),
+                iconPath: activitySuccessIcon
```
Comment (nturinski) [inline src/commands/deployWorkspaceProject/deployWorkspaceProject.ts:74]: This is bit of an aside, but should we have another icon for children that are just relaying information? It's kind of weird to me that we'd have green checkmarks for all of these. 

Not something we need to decide on now, just curious.

File: src/commands/ingress/IngressPromptStep.ts [hunk 6]
```diff
@@ -66,17 +68,17 @@ export async function tryConfigureIngressUsingDockerfile(context: IngressContext
...
-    //             iconPath: activitySuccessIcon
-    //         })
-    //     );
-    // }
+    if (!context.containerApp) {
+        context.activityChildren?.push(
+            new GenericTreeItem(undefined, {
+                contextValue: createActivityChildContext(['ingressPromptStep', activitySuccessContext]),
+                label: context.enableIngress ?
+                    localize('ingressEnableLabel', 'Enable ingress on port {0} (found Dockerfile configuration)', context.targetPort) :
```
Comment (nturinski) [inline src/commands/ingress/IngressPromptStep.ts:76]: I'd prefer we said (from Dockerfile configuration) rather than found.

File: src/commands/deployWorkspaceProject/deployWorkspaceProject.ts (hunk 5 above)
Comment (MicroFish91) [reply src/commands/deployWorkspaceProject/deployWorkspaceProject.ts:74]: Yeah, I agree, it might look cool to experiment with the icons for these

File: src/commands/deployImage/imageSource/buildImageInAzure/BuildImageStep.ts (hunk 1 above)
Comment (MicroFish91) [reply src/commands/deployImage/imageSource/buildImageInAzure/BuildImageStep.ts:47]: `context.image` is a more full version of the image name.  It would include the full azurecr.io/etc...

We wouldn't want to show that as part of the fail output because if this fails, the whole command fails and we wouldn't be able to proceed any further to use the image (I'm assuming the image would fail to build)

File: src/commands/deployImage/imageSource/buildImageInAzure/RunStep.ts (hunk 2 above)
Comment (MicroFish91) [reply src/commands/deployImage/imageSource/buildImageInAzure/RunStep.ts:55]: This one is kind of confusing - my understanding is basically the building starts in this `RunStep`... but the actual meaningful output gets detected in the following step `BuildImageStep`.  Thus, what we want to actually display on success doesn't exist yet, so I defer showing a success output until we can confirm it in the following step.

For the fail, we can still trigger a fail-point within this step, so we should still define the potential fail output here.

File: src/commands/deployWorkspaceProject/deployWorkspaceProject.ts (hunk 5 above)
Comment (MicroFish91) [reply src/commands/deployWorkspaceProject/deployWorkspaceProject.ts:74]: Just playing around with the icon... and these are out of order, but thoughts?

image

**Review by nturinski — APPROVED** [review]
Approving but with expectation some refactors happen in another PR

File: src/commands/deployWorkspaceProject/deployWorkspaceProject.ts (hunk 5 above)
Comment (nturinski) [reply src/commands/deployWorkspaceProject/deployWorkspaceProject.ts:74]: Yeah, I do prefer this. It's still a bit busy in my opinion, but better.

Maybe even just a dash or a bullet point would work?
