### PR TITLE
Remove Activate, Deactivate and Restart Revision Commands when not applicable 

### LINKED ISSUE #163: The revision's state still is inactive after executing "Restart Revision" action for an inactive revision
**OS:** Win10
**Build Version:** 20220719.1
**Regression:** Not a regression

**Repro Steps:**
1. Right click a container app -> Click “Choose Revision Mode...” -> Select "Multiple".
2. Right click an inactive revision -> Click "Restart Revision".
3. Check whether the revision's state is active.

**Expect:**
The revision's state is active.

**Actual:**
The revision's state still is inactive.

### LINKED ISSUE #322: An error occurs when restarting an inactive revision
**OS:** All
**Build Version:** 20230329.6

**Repro Steps:**
1. Change one container app revision mode to "Multiple". 
2. Expand the Revision node and execute "Deactivate Revision" action for one revision.
3. Execute "Restart Revision" action for the above inactive revision.
4. Check whether succeeds to restart an inactive revision or not.

**Expect:**
Succeed to restart an inactive revision.

**Actual:**
An error occurs when restarting an inactive revision.
image

### PR DESCRIPTION
**Pull request by motm32**
Fixes #163.
Fixes #322.

### CODE REVIEW

File: src/commands/revisionCommands/changeRevisionActiveState.ts [hunk 1]
```diff
@@ -18,6 +18,14 @@ export async function executeRevisionOperation(context: IActionContext, node: Co
...
         const revisionName: string = item instanceof RevisionItem ? nonNullProp(item.revision, 'name') : nonNullProp(item.containerApp, 'latestRevisionName');
+
+        if (operation === 'restartRevision') {
+            const revisionData = await appClient.containerAppsRevisions.getRevision(item.containerApp.resourceGroup, item.containerApp.name, revisionName);
+            if (!revisionData.active) {
+                await appClient.containerAppsRevisions['activateRevision'](item.containerApp.resourceGroup, item.containerApp.name, revisionName);
+            }
+        }
+
         await appClient.containerAppsRevisions[operation](item.containerApp.resourceGroup, item.containerApp.name, revisionName);
```
Comment (MicroFish91) [inline src/commands/revisionCommands/changeRevisionActiveState.ts:29]: I think it would be a good idea to put this line in a corresponding else block so that `restartRevision` isn't run immediately after `activateRevision` 🤔

**Review by MicroFish91 — APPROVED** [review]

**Comment by alexweininger** [comment]
boo

**Comment by nturinski** [comment]
Discussed offline: Leverage the `enablement` property rather than just starting up an inactive revision for the user.

**Comment by motm32** [comment]
Enablement does not work in this case so just removing the commands from view when they are not applicable.

File: src/tree/RevisionItem.ts [hunk 2]
```diff
@@ -44,7 +44,7 @@ export class RevisionItem implements RevisionsItemModel {
             label: this.revision.name,
             iconPath: this.iconPath,
             description,
-            contextValue: 'revision',
+            contextValue: `${this.revision.active ? 'active' : 'inactive'};revision`,
```
Comment (alexweininger) [inline src/tree/RevisionItem.ts:47]: The context value string should be created using the `createContextValue` util. It makes sure the values are sorted and deduped.

File: src/tree/RevisionItem.ts [hunk 3]
```diff
@@ -44,7 +44,7 @@ export class RevisionItem implements RevisionsItemModel {
             label: this.revision.name,
             iconPath: this.iconPath,
             description,
-            contextValue: `${this.revision.active ? 'active' : 'inactive'};revision`,
```
Comment (alexweininger) [inline src/tree/RevisionItem.ts]: value passed to `createContextValue` should be like `['active', 'revision']`. The util adds the `;` too.

**Review by alexweininger — APPROVED** [review]
